### ISSUE TITLE
A Guessing Game

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#13]
_This is assignment 13 and is due on Feb 02, 2015._
- Create a guessing game
- The user must guess the number chosen by the app
- Provide feedback to the user as to if their guess is lower or higher than the number
- Count the number of guesses and output at the end

**Comment by brianburridge** [comment]
@RyanZolper this should choose a random number each time so that the answer isn't always 4.

**Comment by RyanZolper** [comment]
fixed that

**Comment by brianburridge** [comment]
:boom:
