### ISSUE TITLE
Classy Pig Latin

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#14]
_This is assignment 14 and is due on Feb 02, 2015._
- Using the structure of a class as I've laid out in this [gist](https://gist.github.com/brianburridge/7e98d358dee03c6b6060), finishing creating the PigLatin class to translate a word into pig latin
- Bonus: modify the app to convert an entire phrase (one word at a time)
- Note the pig latin rules in the comment of the skeleton app

**Comment by brianburridge** [comment]
@RyanZolper you are still working on this one, right? (Just wanted to be sure you didn't forget about it).

**Comment by RyanZolper** [comment]
Sorry, I thought I submitted it. I just re-pushed it.

**Comment by brianburridge** [comment]
Hi @RyanZolper 

This isn't working quite right. It's treating all words the same. Also, it should be returning the modified pigatized text so that the last line displays it. There shouldn't be any `puts` in the class itself.

**Comment by brianburridge** [comment]
I happened to see you committed the piglatin assignment. It's working so I'm going to close, but don't forget to let me know when you finish next time so I can review it. :)

Good to get them checked off as soon as possible.

**Comment by RyanZolper** [comment]
Sorry will do!
