### ISSUE TITLE
Load questions from a file

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#15]
_This is assignment 15 and is due on Feb 02, 2015._
- Copy and then modify assignment 12 to read the questions from a file instead of the hard coded array
- Load them into an array so the rest of the program can remain the same
- If your assignment 12 is coded correctly, you won't have to change the part that asks questions
- Can be done with two lines of code
- Remember to have the text file of questions in the same directory where your Ruby code is

**Comment by brianburridge** [comment]
@RyanZolper remember to check in your questions.txt file, otherwise I cant run and test this.

Also, I'm pretty sure this will throw an error. Did you run this before you turned it in?

**Comment by RyanZolper** [comment]
@brian I ran it and it worked swimmingly. You mean I should add/commit/push the questions file right?

**Comment by RyanZolper** [comment]
I pushed the questions file

**Comment by RyanZolper** [comment]
Actually it threw an error at the end that I didnt notice because I closed the wrong thing... try it now

**Comment by brianburridge** [comment]
:+1:
