### ISSUE TITLE
Extending String with PigLatin

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#20]
_This is assignment 19 and is due on Feb 04, 2015._

Extend Ruby's String class to have a "pigatize" method that will turn any string into pig latin.

Should use the same code you wrote before, but now you are extending the String class and putting the functionality in there.

**Comment by brianburridge** [comment]
This isn't quite what I'm looking for. I should be able to do the following when your class is setup correctly.

```
load 'assignment20.rb'
"hello world".pigatize
```

The _pluralpig_ method you defined besides not being the correct method name, takes a string argument and is a class method. We want an instance method that doesn't take an argument, but instead can be called on a string itself. Much like:

```
  "hello world".size
  "hello world".downcase
  "hello world".pigatize
```

Let me know if you have any questions.

**Comment by RyanZolper** [comment]
fixed

**Comment by brianburridge** [comment]
:boom:
