### ISSUE TITLE
Attributes, accessors, instance variables and private methods

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#21]
_This is assignment 21 and is due on Feb 05, 2015._
- Write a Person class and some code to use it, following the directions below.
## First
- Create a Person class with attributes: first name, last name, and birthdate.
- First name and last name should not be able to be written to, but should be readable.
- Birthdate can be set and read.
- Create a public instance method called `name` that takes the name and sets the first name and last name instance variables. This is so the first name and last name attributes are set by passing in one name.
- Create a public instance method called `age` to calculate and return the user's age.
- Now, outside the Person class, ask the user their information and use it to create the Person object.
- After asking each user their information, output the user's age.
## Next
- Create a class variable that will count the number of people that enter in their information. After you output the person's age, also output the number of person they are so far (using the class variable).
- Loop to allow another user to enter their information. (exit when user enters \q for name). Create a Person object for each user.
- Create a private method called `calculateAge`. This should contain the functionality you previously had in the `age` method. The public `age` method should now call this new private `calculateAge` method.

**Comment by brianburridge** [comment]
One more thing to do here. Separate the person class into it's own `person.rb` so that the class can be loaded without the code running beneath it.

**Comment by RyanZolper** [comment]
reloaded with class in person.rb

**Comment by brianburridge** [comment]
Did you try and run assignment 21?

**Comment by RyanZolper** [comment]
yes after I load person.rb assignment21 works fine

**Comment by brianburridge** [comment]
The load should be inside the assignment 21 code at the top.

**Comment by brianburridge** [comment]
Reminder: let me know when you are ready for me to check this. I looked and saw that you updated it, but this wasn't marked _completed_.

Mostly good at this point, except for the counting with the class variable. That should be done in an initializer, so when a person object is created it's done automatically. Then the _personcount_ method shouldn't change the count, but just report it.

**Comment by brianburridge** [comment]
:+1:
