### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#23]
_This is assignment 23 and is due on Feb 09, 2015._
- Create an InvoiceItem class and an Invoice class (two classes in two separate files)
- The InvoiceItem class should have the following attributes: product_name, sale_price, quantity, tax percentage
- The invoice class should have a getter and setter for an attribute called: _items_ to hold an array of all the InvoiceItems
- Create an instance method in Invoice that will calculate a total of all it's invoice items
- Use reject or select methods in order to remove any InvoiceItem objects that have a zero quantity
- Create an instance method in Invoice to sum up the invoice items and get a total
- Ask the user to enter in the attributes for each invoice item, hitting ENTER on product name when done
- With each invoice item entered, create the object and add it to the collection of invoice items within a single Invoice object.
- Then output each line item.
- Show a sub-total without the tax, then a line item for the tax, then the total.
- Bonus: make the invoice look like a real world invoice in the terminal

**Comment by RyanZolper** [comment]
pushed with my classes in invoice.rb and invoiceitem.rb

I'm not sure if this is exactly what you want so let me know if you want me to change things

**Comment by brianburridge** [comment]
Where is the code that prompts the user to enter in all the invoice information?

Also, in InvoiceItem, you have created getters for attributes sale_price, quantity, and tax_percentage. But those are unnecessary because Ruby created them for you when you used `attr_accessor`.

**Comment by RyanZolper** [comment]
I accidentally name that code assignment22.rb, I changed it to
assignment23.rb and pushed it. I also cleaned up the code so I didn't
create unnecessary getters.

**Comment by brianburridge** [comment]
:+1:
