### ISSUE TITLE
Hiring and Firing Employees

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#24]
_This is assignment 24 and is due on Feb 09, 2015._
- Take the Employee and Company classes, and create functionality to allow the company to hire and fire an employee.
- Create a Ruby app that will use those classes to do the following:
- prompt the user to enter information for the company.
- prompt the user to enter each employee. It will then "hire" each of them.
- show a list of employees, with ids, then ask the user if they would like to fire an employee by entering that id.
- fire the employee by id and show an updated list with that employee no longer in it.

**Comment by RyanZolper** [comment]
completed with classes in company.rb and employee.rb

**Comment by brianburridge** [comment]
This works, but the implementation isn't quite correct.

The collection (Array) of employees should go into the Company object, as a `employees` attribute.

It would also be better if the code to list out those employees to the screen was a method on company, so it can be re-used (ex. called before and after the firing is done).

**Comment by RyanZolper** [comment]
fixed

**Comment by brianburridge** [comment]
Closer. But, the array should be of Employee objects. You are creating employee objects but not using them anywhere. Instead, you are creating another array and then making the employees be an array of arrays.

Note, you have a stray variable assignment on line 4 of your Company class.

Also, in _assignment24.rb_ why do you need both `a` and `x` for counters? In fact if you use the `Array.push` method you don't need a counter at all. Take a look at that.

**Comment by brianburridge** [comment]
:+1:
