### ISSUE TITLE
More work with classes, getters and setters (in class, pairing)

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#26]
_This is assignment 25b and is due on Feb 10, 2015._
- Design and code a Blog and Post class.
- These classes should model a system where a user can create a blog, which will have posts.
- A Blog can have a name, a user_name, and the collection of posts
- A Post can have a name, a summary, the body of the post, the published date, and a word count.
- Since both a blog and a post MUST have a name, override the initializer so that when an object of either class is created, a name must be supplied.

**Comment by RyanZolper** [comment]
pushed assignment25.rb blog.rb and post.rb

**Comment by brianburridge** [comment]
Blog and post should require a `name` via a custom (overridden) initializer.

Other than that, I think you have everything else correct.

**Comment by RyanZolper** [comment]
fixed

**Comment by brianburridge** [comment]
Hey @RyanZolper 

For this, what I'm looking for is to have the initializer accept `name` as an argument so that developer instantiating a Blog object has to pass a name. Same with Post.

**Comment by brianburridge** [comment]
@RyanZolper did you make the changes to this one?

**Comment by RyanZolper** [comment]
Yup

**Comment by brianburridge** [comment]
Don't forget to add the _completed_ tag when you are ready for me to review it.

**Comment by brianburridge** [comment]
I'm not seeing the changes. Still looks the same.

**Comment by brianburridge** [comment]
@RyanZolper I'm removing the completed tag on this because the changes have not been made, at least not in GitHub. Please see me after class so we can be sure you understand what I meant needed to be fixed on this one.

**Comment by brianburridge** [comment]
:+1:
