### ISSUE TITLE
Blog Rails App

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#32]
_This is assignment 31 and is due on Feb 16, 2015._
- Review the [UrlHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html)
- Review the [AssetTagHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html)
- Review the [table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table) HTML tag
- Create a new Rails app. It should go inside your _assignments_ repository.
- This will be a blog app.
- You'll want a posts controller with an index action and actions for the individual posts.
- The "root" of your blog app should be the posts index page, showing links to the posts.
- Add an about me page with real information about yourself. This should go in a 'welcome' controller. Tip: don't forget to setup your routes.
- Use Twitter Bootstrap to make this look as nice and as real as you can make it. I'm going to pick the best and show it to other instructors at TIY in our weekly meeting. Remember you can install Bootstrap using the simple CDN method.
- Create and use at least one helper method. It could be used to format a date, for example.
- Use the image_tag in at least one place.

**Comment by RyanZolper** [comment]
Hope mine is the best!

**Comment by brianburridge** [comment]
:+1:
