### ISSUE TITLE
Movie Query app form - in class

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#33]
_This is assignment 32 and is due on Feb 17, 2015._
- Change your movie query app and add an HTML form to prompt the user for a movie title and submit to the controller/action you already have.
- You can still use the HTTP GET method in this case, because we want the old way of passing it in the request url to work.
- Use bootstrap to improve the look of the form.
- Refer to [Bootstrap form stylings](http://getbootstrap.com/css/#forms)
- Refer to [Rails form helpers](http://guides.rubyonrails.org/form_helpers.html)

**Comment by brianburridge** [comment]
Hi @RyanZolper 
In movies_controller, the home method, you have an initialize method nested inside another method. Technically ruby allows that, but that serves no purpose here. What were you attempting to do there? What is the purpose of the initialize method inside the action?

**Comment by RyanZolper** [comment]
that was leftover from when I was experimenting at the start of the
afternoon. It was unnecessary and I removed it.

**Comment by brianburridge** [comment]
:+1:
