### ISSUE TITLE
Multipe models, Scaffolding, and Heroku Deploys

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#36]
_This is assignment 35 and is due on Feb 23, 2015._
- Create a new Rails app, in it's own folder (not within the previous _Assignments_ folder)
- This new Rails app should have three models. Two of them should have scaffolds. They should all have associations, so pick three models that are related in some way.
- Ensure all associations can be set within your Rails app views (no longer just in the console)
- On the index view of a parent model, show the count of children it has (the has_many relationship). Example: how many books does that library have?
- Add a _Procfile_ to your app with this line: `web: bundle exec thin start -p $PORT` (note: this is to get it working on Heroku)
- Add the following to your Gemfile (please read the comments to remind yourself why each Gem is necessary):
  
  ```
  # User the 'thin' server instead of the default webrick
  gem 'thin'
  
  # Use postgres and the Heroku rails gem for Heroku
  group :production do
    gem 'rails_12factor'
  end
  ```
- Deploy to Heroku
- When you submit the assignment, paste the URL to your Heroku app in a comment within this issue.

**Comment by RyanZolper** [comment]
https://infinite-hamlet-3727.herokuapp.com/

**Comment by brianburridge** [comment]
@RyanZolper I'm not able to see the code. Looks like you might have checked assignment 35 in as a submodule? If you look in your repo you can see that there is nothing under the assignment 35 folder.

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/Assignment36

**Comment by brianburridge** [comment]
@RyanZolper why do you have a model called _Model_? What does that represent?

When I tried to create a company, it crashed (on Heroku).

**Comment by RyanZolper** [comment]
I have no idea why it doesn't run on Heroku... it runs locally and it is up
to date with heroku. how do I look at heroku logs?

Company has_many models which has many configurations I.E Company: BMW,
Model: 3-series, Configuration: 335is

**Comment by brianburridge** [comment]
```
    heroku logs --tail
```

Then run it on heroku to create the errors and they will show up in the logs.

**Comment by RyanZolper** [comment]
fixed on heroku

**Comment by brianburridge** [comment]
@RyanZolper tried to create a company with a logo and Heroku gave me an error.

**Comment by RyanZolper** [comment]
fixed this

**Comment by brianburridge** [comment]
:+1:
