### ISSUE TITLE
Seed Data and Image Uploading

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#37]
_This is assignment 36 and is due on Feb 24, 2015._
- Add some seed data to assignment 35 using the Faker gem.
- Add image upload support to your Rails app from assignment 35, using [CarrierWave gem](https://github.com/carrierwaveuploader/carrierwave).
- You can add image uploads to any existing models in that app.
- For this assignment, use _file_ storage.
- Your user should be able to browse for a local image and upload it along with your other model attributes in the form.
- The uploaded images should show on both the index page (thumbnail size) and the show page (a larger size).
- Feel free to experiment with sizes and versions.
- Please include the URL to your Github repo for this app in a comment in this issue.
- Note: do not deploy this to Heroku yet

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/OtherAssignments/tree/foo

**Comment by brianburridge** [comment]
@RyanZolper what app is this compared with this one: https://github.com/RyanZolper/Assignment36

**Comment by RyanZolper** [comment]
It's the same... you said I could just keep updating the same repo

**Comment by brianburridge** [comment]
Except, they are not the same.

Compare these two seed files for example:
https://github.com/RyanZolper/OtherAssignments/blob/foo/db/seeds.rb
https://github.com/RyanZolper/Assignment36/blob/master/db/seeds.rb

I don't really know which one to look at to review.

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/OtherAssignments/tree/foo

This one. This was the assignment I was having issues deploying properly.

After this assignment all my work for that app is in the Assignment36 repo

**Comment by brianburridge** [comment]
@RyanZolper you are creating only one record with your seed data. I'm looking for much more than that. It should be a seed file that creates records for all your models, including an image upload for the Company logo.

**Comment by RyanZolper** [comment]
fixed this

**Comment by brianburridge** [comment]
This seed file hasn't changed: https://github.com/RyanZolper/OtherAssignments/blob/foo/db/seeds.rb

And that's where you said I should look three comments back.

**Comment by brianburridge** [comment]
@RyanZolper Please take a look at this again.

**Comment by RyanZolper** [comment]
Can you please use my assignment 36 repo for this assignment? I made the
more in depth seed file in this repo.

**Comment by brianburridge** [comment]
I looked here this time: https://github.com/RyanZolper/Assignment36/blob/master/db/seeds.rb

Looks good. :+1:
