### ISSUE TITLE
CarrierWave, S3 and environment varaibles

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#38]
_This is assignment 37 and is due on Feb 25, 2015._
- Convert the app from assignment 36 to use [Amazon S3, via Fog](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3), instead of local file storage.
- Remember to use the [dotenv gem](https://github.com/bkeepers/dotenv) and `heroku config` so you aren't storing your S3 private access keys in GitHub
- Deploy to Heroku (and GitHub as always)
- Please provide the link to the repo AND your Heroku app in a comment here.

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/Assignment36
https://git.heroku.com/infinite-hamlet-3727.git

**Comment by brianburridge** [comment]
Same problem here. I can't upload a company logo. I get an error.

**Comment by RyanZolper** [comment]
fixed this

**Comment by brianburridge** [comment]
:+1:
