### ISSUE TITLE
Adding a User model and scoping your app to the current user

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#40]
_This is assignment 39 and is due on Feb 26, 2015._
- Modify the app from assignment 36-38, to have a User model
- Also, modify any models that should be scoped to a User, to belong to a user object
- Only show the user's records when in that context
- Create a User guest record in the seed file
- Default your app to always use that User
- Modify at least one model's create to be automatically associated with that User when it's created.
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by RyanZolper** [comment]
Do we use the 'devise' gem or anything else to help create the user model?

**Comment by RyanZolper** [comment]
https://git.heroku.com/infinite-hamlet-3727.git
https://github.com/RyanZolper/Assignment36

**Comment by brianburridge** [comment]
@RyanZolper we skip the user creation and using Devise for now.

**Comment by brianburridge** [comment]
@RyanZolper In your companies controller you have this line: `@company.user_id = 1`

That isn't setting the company to be the guest record, that's setting it to be the User with an id of 1. Our goal for this assignment was to create the `current_user` method in the `application_controller`. Then you can always get the "current user" to auto assign new objects to. This was the first step as we moved toward full authentication.

Also part of this was to scope the model (company in your case) to the user, so that when the user looks at the companies index they only see the companies they own.

**Comment by RyanZolper** [comment]
fixed

**Comment by brianburridge** [comment]
:+1:
