### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#41]
_This is assignment 40 and is due on Feb 26, 2015._
- Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
- Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
- Create an active admin resource for every model in your app
- Do some customization
- Ensure all forms save and allow the user to set the relationships
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by RyanZolper** [comment]
https://git.heroku.com/infinite-hamlet-3727.git
https://github.com/RyanZolper/Assignment36

**Comment by brianburridge** [comment]
Users and Companies don't load in active admin.

Also, each resource should be in it's own admin class (so you'd have user.rb, company.rb, etc). The ActiveAdmin documentation shows running a resource generator for each model.

**Comment by RyanZolper** [comment]
Everything loads fine on my end, don't know what the issue is. in user.rb I
have all of the different admin classes nested under user class. I
initially ran a resource generator for each but I changed it to reflect the
associations better (in my mind at least)

**Comment by brianburridge** [comment]
It's not working on heroku though. You'll need to look at your heroku logs to see the error and troubleshoot.

```
    heroku logs --tail
```

They should be in individual files. Too confusing to put them all together in the same class.

**Comment by RyanZolper** [comment]
now its running properly on heroku

**Comment by brianburridge** [comment]
Eek! Have you taken a look at active admin for this app? It's quite broken. Hard to test this.

**Comment by RyanZolper** [comment]
fixed

**Comment by brianburridge** [comment]
Better, but I"m unable to edit a Company

**Comment by RyanZolper** [comment]
Fixed... interesting that Active Admin requires :country attributes to use
a dropdown menu for editing

**Comment by brianburridge** [comment]
:+1:
