### ISSUE TITLE
Build Pinterest

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#43]
_This is assignment 42 and is due on Mar 02, 2015._
- Should have these models: User, Pin, Board
- The home page should show "pins" from all users, and not in a table format but a grid
- Should use pagination with Kaminari on the pin page
- User should be able to create new pins, uploading an image to represent them.
- A Pin should have these attributes and belong to the user who added it: title, description, board, url, pin image
- A user should be able to create boards to pin items to. Every pin belongs to one board. A board has a name and belongs to a user.
- When the user clicks on a pin from the home page, it can either pop the pin up like Pinterest does, or go to a separate show page.
- There should be a search form to search the descriptions of the pins and show those matching (across all users).
- There should be a nav providing links to the home page, the user's pins, and the user's boards
- Bonus: make it look amazing!

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/FakePin

**Comment by RyanZolper** [comment]
https://rocky-depths-9918.herokuapp.com/

**Comment by brianburridge** [comment]
I'm not able to create a board, which means I can't test pinning anything either.

**Comment by brianburridge** [comment]
@RyanZolper can you take a few minutes and look at the board creation? I would bet it's a quick fix and that it would unlock me a being to test and close off your remaining assignments.

**Comment by RyanZolper** [comment]
Oh, sorry. I fixed this the other day.

**Comment by brianburridge** [comment]
This app has some serious UI problems, but we'll work on that while you are on your final project. :)

:+1:
