### ISSUE TITLE
Restricting ActiveAdmin access

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#46]
_This is assignment 44 and is due on Mar 05, 2015._
- Adjust your Pinterest app to only allow "admin" users to access the /admin section

**Comment by RyanZolper** [comment]
https://github.com/RyanZolper/FakePin
https://git.heroku.com/rocky-depths-9918.git

**Comment by brianburridge** [comment]
:+1:
