### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#50]
_This is assignment 48 and is due on Mar 11, 2015._
- Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
- Try [Dash](http://kapeli.com/dash)
- Try [OmniRef](https://www.omniref.com/)
- Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
- Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
- Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
- Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by RyanZolper** [comment]
Pin Load (1.4ms)  SELECT "pins".\* FROM "pins"  ORDER BY created_at DESC
All pins inspected: #<ActiveRecord::Relation [#<Pin id: 1, title: "Sample 1", description: "yadayadyadaydaydayadya", url: nil, created_at: "2015-03-10 18:08:33", updated_at: "2015-03-10 18:08:33", user_id: 30, board_id: nil, pinimage: "NJvCwj3.jpg">]>

In my pins_controller file, in the index action, in the "else" if the second "if" statement, I have the logger inspect and output all of the pins, @pins.

**Comment by RyanZolper** [comment]
Pin Load (2.0ms)  SELECT "pins".* FROM "pins"  ORDER BY created_at DESC
All pins inspected: #<ActiveRecord::Relation [#<Pin id: 1, title: "Sample 1", description: "yadayadyadaydaydayadya", url: nil, created_at: "2015-03-10 18:39:08", updated_at: "2015-03-10 18:39:08", user_id: 30, board_id: nil, pinimage: "NJvCwj3.jpg">]>

**Comment by RyanZolper** [comment]
"SELECT "pins".* FROM "pins"  ORDER BY created_at DESC
All pins inspected: #<ActiveRecord::Relation [#<Pin id: 1, title: "Sample 1", description: "yadayadyadaydaydayadya", url: nil, created_at: "2015-03-10 18:39:08", updated_at: "2015-03-10 18:39:08", user_id: 30, board_id: nil, pinimage: "NJvCwj3.jpg">]>"

**Comment by RyanZolper** [comment]
![image](https://cloud.githubusercontent.com/assets/10709598/6583067/14fcf9b4-c738-11e4-8ae4-df00f642b96c.png)

Copy and paste of log comment doesn't work for some reason

**Comment by brianburridge** [comment]
:+1:
