### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#57]
_This is assignment 56 and is due on Mar 23, 2015._
- Review the [Rails testing guide](http://guides.rubyonrails.org/testing.html)
- Using your Pinterest app and conventional built in testing (note: you can load the testing db using any preferred means).
- Write some unit tests to check that all the models will not save unless they have valid data (testing the validations).
- Write a functional test to ensure the home page comes up with the proper data on it.
- Write a functional test to ensure clicking on a pin link display the correct view.
- Write a functional test to ensure the search works correctly.
- Write an integration test to ensure there is a nav providing links to the home page, the user's pins, and the user's boards
- Write an integration test to ensure only admins can get to the admin section.
- Write an integration test to ensure users can only see their own pins and only when they are logged in.

**Comment by brianburridge** [comment]
@RyanZolper Run `rake` to run all your tests in this app. you'll see there are 11 failures. Maybe those are the tests that were auto-generated and not the ones you created. If so, delete the ones that you didn't set up. You should be able to run `rake` to run all your tests successfully.

**Comment by RyanZolper** [comment]
Yeah those were automatically generated. I'll delete them.

**Comment by RyanZolper** [comment]
After changing my current_user helper from a cookie to a session variable, I'm working out some testing bugs, please check this assignment later

**Comment by RyanZolper** [comment]
done

**Comment by brianburridge** [comment]
:+1:
