### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#6]
_This assignment is due on Jan 28, 2015._
- Create a Ruby script to ask the user for their name and then wish them a Happy Birthday by name
- Add some comments to your code
- Put this code in a gist and paste the link from the gist in a comment of this issue
## Bonus
- Add another prompt for birthdate
- Show the birth date in parenthesis after the greeting
- Note: user must enter date in like: 2014/09/22 or 2014-09-22
- Change the output formatting to: Friday, April 1, 1974
- Capitalize the user's name

**Comment by RyanZolper** [comment]
https://gist.github.com/RyanZolper/9ba617a9e9d771beb15b

**Comment by brianburridge** [comment]
@RyanZolper didn't quite follow the instructions.
For the top part, it needs to output the user's name (using string interpolation).

For the bonus part, the date must be formatted as shown.

**Comment by RyanZolper** [comment]
@brianburridge not really sure what I did wrong in the top part....

Figure out the date manipulation though!

birthday =  raw.strftime("%A" ", "  "%B" " " "%d" ", " "%Y")

**Comment by brianburridge** [comment]
@RyanZolper you didn't do anything wrong, you just didn't remember to output the user's name. So after they enter it, you should say something like, "Hi " and their name.

For the strftime, those symbols should be all in one string, instead of numerous strings. 

Also, update your gist with the latest code so I can see the updates. Thanks.

**Comment by brianburridge** [comment]
@RyanZolper this doesn't run the way it is now. Be sure to run your code at the command line before submitting it.

**Comment by RyanZolper** [comment]
better now?

**Comment by brianburridge** [comment]
Formatting for the date is still in separate strings and you have several lines of code repeated that shouldn't be. (Maybe just a copy/paste issue).

**Comment by brianburridge** [comment]
Hey @RyanZolper , this one still isn't working properly. Put this into a _happy_birthday.rb_ in your assignments folder and get it running from there. You'll be able to see better where the problem is.

**Comment by RyanZolper** [comment]
The one I have is working fine. I titled it happy_birthday.rb and pushed it
to my AssignmentsIronYard folder. Sorry if I didn't submit the final
working one properly.

**Comment by brianburridge** [comment]
Cool, looks good!
:+1:
