### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#61]
_This is assignment 59 and is due on Mar 26, 2015._
- Add a [jQuery plugin](http://plugins.jquery.com/) to your Pinterest app
- Be sure to direct me to where on your app you've added it, both in your code and what page it's running on at Heroku so I can see it work.

**Comment by RyanZolper** [comment]
Added an autocomplete plugin to the search bar in the index page.

Plugin uses 'jquery.autocomplete.js' and 'jquery.autocomplete.js' in vendor/assets
I wrote the code to init the function in 'autocomp.js' in assets.

The application layout calls the required files and references google's jquery api.

**Comment by brianburridge** [comment]
I'm not able to login on your app on heroku to test this out. Can you take a look at that?

**Comment by RyanZolper** [comment]
My login works fine even with a new user. I had to reset my pg db so your
user object probably got deleted. I'll take a look at why the proper
redirect isn't working (and fix one other little problem) and then I'll
remark this as complete

**Comment by RyanZolper** [comment]
Fixed

**Comment by brianburridge** [comment]
Can't test completely right now because I Can't create my first board.

**Comment by brianburridge** [comment]
:+1:
