### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#62]
_This is assignment 60 and is due on Mar 30, 2015._
- Review the Rails guide on [Working with JavaScript in Rails](http://guides.rubyonrails.org/working_with_javascript_in_rails.html)
- Refer to the [CoffeeScript docs](http://coffeescript.org/)
- Write some CoffeeScript in your Pinterest app to listen for a click on the header/logo of your app (in the nav), and when clicked, popup a bootstrap modal with some about information for your app.
- Bonus: Use Ajax in one place in your Pinterest app (deleting an item, adding an item, etc)

**Comment by brianburridge** [comment]
@RyanZolper did you ever do this task? This is probably about a 15 minute assignment for you. :)

**Comment by RyanZolper** [comment]
Forgot about that one... completed!

**Comment by brianburridge** [comment]
:+1:
