### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by RyanZolper** [comment]
2.2.0 :031 > # Create a String variable named 'name'
2.2.0 :032 >  
2.2.0 :033 >   name = "Ryan"
 => "Ryan" 
2.2.0 :034 > 
2.2.0 :035 >   # Create a Date variable named "a_date"
2.2.0 :036 >  
2.2.0 :037 >   require 'date'
 => true 
2.2.0 :038 > 
2.2.0 :039 >   a_date = Date.new(2010,12,12)
 => #<Date: 2010-12-12 ((2455543j,0s,0n),+0s,2299161j)> 
2.2.0 :040 > 
2.2.0 :041 >   # Create an integer variable named "age"
2.2.0 :042 >  
2.2.0 :043 >   age = 20
 => 20 
2.2.0 :044 > 
2.2.0 :045 >   # Create an array of names named 'names'
2.2.0 :046 >  
2.2.0 :047 >   names = ["george", "steve", "bob"]
 => ["george", "steve", "bob"] 
2.2.0 :048 > 
2.2.0 :049 >  
2.2.0 :050 >   # Create another array, using %w, named 'more_names'
2.2.0 :051 >  
2.2.0 :052 >   more_names = %w(john bon jovi)
 => ["john", "bon", "jovi"] 
2.2.0 :053 > 
2.2.0 :054 >  
2.2.0 :055 >   # Create a Hash of names with ages named 'names_and_ages'
2.2.0 :056 >  
2.2.0 :057 >   names_and_ages = {ryan:20, jack:90}
 => {:ryan=>20, :jack=>90} 
2.2.0 :058 > 
2.2.0 :059 >   # Keep this part as a way to test your code
2.2.0 :060 >   puts name.class
String
 => nil 
2.2.0 :061 > puts a_date.class
Date
 => nil 
2.2.0 :062 > puts age.class
Fixnum
 => nil 
2.2.0 :063 > puts names.class
Array
 => nil 
2.2.0 :064 > puts more_names.class
Array
 => nil 
2.2.0 :065 > puts names_and_ages.class
Hash
 => nil 
2.2.0 :066 > 
2.2.0 :067 >   puts name.is_a? String
true
 => nil 
2.2.0 :068 > puts a_date.is_a? Date
true
 => nil 
2.2.0 :069 > puts age.is_a? Fixnum
true
 => nil 
2.2.0 :070 > puts names.is_a? Array
true
 => nil 
2.2.0 :071 > puts more_names.is_a? Array
true
 => nil 
2.2.0 :072 > puts names_and_ages.is_a? Hash
true
 => nil 
2.2.0 :073 > 
2.2.0 :074 >   # Create a String literal and output it's class (one line)
2.2.0 :075 >  
2.2.0 :076 >   "brooo".class
 => String 
2.2.0 :077 > 
2.2.0 :078 >   # Create a Fixnum literal and output it's class (one line)
2.2.0 :079 >  
2.2.0 :080 >   23.class
 => Fixnum 
2.2.0 :081 > 
2.2.0 :082 >   # Create an Array literal and output it's class (one line)
2.2.0 :083 >  
2.2.0 :084 >   %w(hi how are you).class
 => Array 
2.2.0 :085 > 
2.2.0 :086 >   # Create a Hash literal and output it's class (one line). Note to keep from confusing Ruby you'll have to wrap what you are outputting in parenthesis
2.2.0 :087 >  
2.2.0 :088 >   {me:"gorgeous", you:"ew"}.class
 => Hash 
2.2.0 :089 > 
2.2.0 :090 >   # Create a symbol and output it's class
2.2.0 :091 >  
2.2.0 :092 >   :bruh.class
 => Symbol 
2.2.0 :093 > 
2.2.0 :094 >   # Create a String constant with any name you choose
2.2.0 :095 >  
2.2.0 :096 >   "ilovestrings".to_s
 => "ilovestrings" 
2.2.0 :097 > 
2.2.0 :098 >   # Change the value of that constant
2.2.0 :099 >  
2.2.0 :100 >   "ilovestrings"
 => "ilovestrings" 
2.2.0 :101 > 
2.2.0 :102 >   # Output the constant's value to the screen
2.2.0 :103 >  
2.2.0 :104 >   "ilovestrings".object_id
 => 70120542391460 
2.2.0 :105 >

**Comment by brianburridge** [comment]
@RyanZolper Everything is good except the constants part. Read up on what a constant is in Ruby and tweak that part of it.

**Comment by RyanZolper** [comment]
# Create a String constant with any name you choose

CONSTANT = 10

# Change the value of that constant

CONSTANT = 11

# Output the constant's value to the screen

11

My bad on being hung up on strings. So basically a string constant is when
you want a variable to stay constant throughout your program. Ruby gives
you a warning when you change the constant but it still allows you to
change it. I wrote this email because I think you closed assignment 7 on me.

**Comment by brianburridge** [comment]
That's correct. The issue wasn't closed yet though. :) And even if it was you can still comment on it.

Now I'm closing it though. :+1:
