### ISSUE TITLE
Working with Loops

### ISSUE THREAD

**Issue by brianburridge** [RyanZolper/AssignmentsIronYard#8]
_This assignment is due on Jan 29, 2015._
- Request input of a number from the user.
- Iterate the number of times indicated by the input number
- Within the loop, print the number of the iteration
- Do this for each of these methods of looping: while, for i in rage, loop, until, .times with counter, until, range
- All should print from 1 to the number input by the user

**Comment by brianburridge** [comment]
@RyanZolper you have a big in your assignment8.rb. Try to run it at the command line.

**Comment by RyanZolper** [comment]
I didn't even need to run it... I forgot to redefine "n" each time...

**Comment by brianburridge** [comment]
@RyanZolper you do need to run it

**Comment by RyanZolper** [comment]
Is there a way to run it without going line by line?

**Comment by brianburridge** [comment]
@RyanZolper assignment 8 can't be run. It gives an error.

**Comment by RyanZolper** [comment]
Odd, I can run it without a problem

**Comment by brianburridge** [comment]
:+1: 

:smile:
